### ISSUE TITLE
Missing Manual button and segmentation buttons

### ISSUE THREAD

**Issue by Rotoslider** [VUKOZ-OEL/3d-forest#1]
I built this on a Windows 10 x64 machine with no errors following your instructions "Build Using "MinGW Makefiles" on Windows".
I also used the "Generate Help Manuals" instructions to build the qhc and qch files. Files were created and placed in the bin/documentation folder. See screen shot. Missing the Manual tab under Help.
I was able to load a las file and classify the ground. Then I tried to use segmentation to split forest into trees. There appears to be some missing buttons. See screen shot
![3d forest2 missing buttons](https://user-images.githubusercontent.com/15005663/171774354-9ade8e52-c1ec-41e2-b22c-2f2e80a5c2ca.png)

**Comment by janekT** [comment]
HI this version is in development and some methods are not implemented yet. For production use try to install older version from https://github.com/VUKOZ-OEL/3d-forest-classic
