### ISSUE TITLE
Error in my 5 step for installation

### ISSUE THREAD

**Issue by ulimaps** [VUKOZ-OEL/3d-forest#2]
In the 5 step for installation, when I do:

$ cmake -G "Unix Makefiles" .. -DCMAKE_INSTALL_PREFIX=..

the results is:

[ 57%] Linking CXX executable 3DForestClassification
/usr/bin/ld: ../../../core/lib3DForestCore.so: referencia a `pthread_create' sin definir
collect2: error: ld returned 1 exit status
make[2]: *** [src/apps/tools/classification/CMakeFiles/3DForestClassification.dir/build.make:101: src/apps/tools/classification/3DForestClassification] Error 1
make[1]: *** [CMakeFiles/Makefile2:575: src/apps/tools/classification/CMakeFiles/3DForestClassification.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Could you help me, please?

**Comment by VaclavBubnik** [comment]
Have you tried to follow all build steps for Linux? I am building 3D Forest on Linux by using [Linux build from source code](https://vukoz-oel.github.io/3d-forest-documentation/3d-forest-developer-guide.html#build-linux-make) guide. It is working for me on Ubuntu.

**Comment by tempdeltavalue** [comment]
Do we really need to download 30 gb for Qt ?

**Comment by tempdeltavalue** [comment]
also issue on win10 (also I didn't figure out how to launch this into vs (I tried run with existed code))

mingw32-make[2]: *** [src/core/CMakeFiles/3DForestCore.dir/Error.cpp.obj] Error 1
CMakeFiles\Makefile2:534: recipe for target 'src/core/CMakeFiles/3DForestCore.dir/all' failed
mingw32-make[1]: *** [src/core/CMakeFiles/3DForestCore.dir/all] Error 2
Makefile:134: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by VaclavBubnik** [comment]
The easy way with vs is just to open cloned '3d-forest' folder as 'Open with Visual Studio'. Everything is then created automatically by vs. There is no need to create some sln. The following steps are working for me https://vukoz-oel.github.io/3d-forest-documentation/3d-forest-developer-guide.html#build-windows-visual-studio (but i can not give you my computer).

**Comment by sobhonium** [comment]
When I run
>> cmake -G "Unix Makefiles" .. -DCMAKE_INSTALL_PREFIX=..

I get this from terminal:

-- GCC compiler detected, adding compile flags
CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:35 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at CMakeLists.txt:46 (find_package):
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.


-- Gui with Qt5 and OpenGL found
-- BUILD_EXAMPLES not set - skipping examples
-- BUILD_TESTS not set - skipping tests
-- BUILD_DEVEL not set - skipping 3DForestIcon
-- BUILD_DEVEL not set - skipping 3DForestSandbox
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sbn/Documents/forest/3d-forest/build

**Comment by VaclavBubnik** [comment]
3D forest should be just trying to find Qt6. It seems that this creates unexpected amount of configuration messages on some systems which have only Qt5. CMake command line option `-DFORCE_QT5=ON` should disable Qt6 auto detection but that should not be necessary. I will look into it.

**Comment by VaclavBubnik** [comment]
Linux build instructions and CMake files have been updated to resolve the issue.
