### ISSUE TITLE
 undefined reference to `pthread_create'

### ISSUE THREAD

**Issue by Guoc0529** [VUKOZ-OEL/3d-forest#7]
Scanning dependencies of target 3DForestClassification
[ 40%] Building CXX object src/apps/tools/classification/CMakeFiles/3DForestClassification.dir/classification.cpp.o
[ 40%] Building CXX object src/apps/tools/classification/CMakeFiles/3DForestClassification.dir/__/__/__/plugins/classification/ClassificationAction.cpp.o
[ 41%] Linking CXX executable 3DForestClassification
/usr/bin/ld: ../../../core/lib3DForestCore.so: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[2]: *** [src/apps/tools/classification/CMakeFiles/3DForestClassification.dir/build.make:101：src/apps/tools/classification/3DForestClassification] 错误 1
make[1]: *** [CMakeFiles/Makefile2:858：src/apps/tools/classification/CMakeFiles/3DForestClassification.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2

Hello, I encountered a linking error while compiling the 3D Forest project. thanks！

**Comment by Guoc0529** [comment]
I want to thank you for your valuable work and contributions. I found a solution to the undefined reference to 'pthread_create' error in your blog on CSDN, which helped me resolve the issue in my C++ project. Your insights are greatly appreciated, and they make a positive impact on the community!
https://blog.csdn.net/qq_40301351/article/details/143141667

**Comment by VaclavBubnik** [comment]
Perfect. Additionally, this issue should be fixed in the latest Git version.
