### ISSUE TITLE
GUI differs from provided images - missing functionalities

### ISSUE THREAD

**Issue by Guoc0529** [VUKOZ-OEL/3d-forest#8]
![2024-10-22 16-23-15屏幕截图](https://github.com/user-attachments/assets/f02079ed-27ff-42ee-914c-3178c430c6bf)
Thank you for your work on the 3D Forest project!

I successfully compiled the project following the instructions, and everything seemed to build correctly. However, when I run the application, the graphical interface looks different from the screenshots provided in the documentation or examples. Specifically, many functionalities seem to be missing or not displayed in my version of the GUI.

I've checked the build process and ensured that all dependencies (like Qt and OpenGL) are installed and correctly configured, but I still can't figure out what might be causing the issue.

Could you provide any guidance or suggestions on how to resolve this? I'd really appreciate your help!

**Comment by VaclavBubnik** [comment]
Thank you for bringing this to my attention. I'll take a closer look at the issue and get back to you with any updates or suggestions as soon as possible.

**Comment by Guoc0529** [comment]
> Thank you for bringing this to my attention. I'll take a closer look at the issue and get back to you with any updates or suggestions as soon as possible.

Thank you for your reply! I've identified the reason for the bug — it appears some libraries didn’t compile successfully, which is why those buttons weren’t displayed on the interface.

Thanks again!

**Comment by VaclavBubnik** [comment]
I made a few bug fixes to build the latest version on Linux.
However, there is still a rendering bug on Linux that caused it to crash. And I do not see any icons in the latest version.

I am using the following commands:
```
$ cd /home/user/
$ git clone https://github.com/VUKOZ-OEL/3d-forest.git
$ cd /home/user/3d-forest/
$ mkdir build
$ cd /home/user/3d-forest/build/
$ PATH=$PATH:/home/user/Qt/5.15.0/gcc_64/bin
$ cmake -G "Unix Makefiles" .. -DCMAKE_INSTALL_PREFIX=..
$ make
$ make install
$ cd /home/user/3d-forest/bin/
$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/user/3d-forest/bin:/home/user/Qt/5.15.0/gcc_64/lib ./3DForest
```

![Screenshot-2024-11-01-132024](https://github.com/user-attachments/assets/28a8f6fe-8263-4545-a707-a631ca6be66c)
